kind: ConfigMap
apiVersion: v1
metadata:
  name: ui-interface-config
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          enabled: true
          reload:
            enabled: true
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: hello-service
              uri: lb://hello-service
              predicates:
                - Path=/hello-service/**

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-interface-deployment
  labels:
    app: ui-interface
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: ui-interface
  template:
    metadata:
      labels:
        app: ui-interface
    spec:
      containers:
        - name: ui-interface
          image: mrflick72/ui-interface:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ui-interface-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
---

kind: Service
apiVersion: v1
metadata:
  name: ui-interface
spec:
  selector:
    app: ui-interface
  ports:
    - protocol: TCP
      port: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-interface-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /ui/?(.*)
            backend:
              serviceName: ui-interface
              servicePort: 8080
