ribbon:
  eureka:
    enabled: false
  client:
    enabled: true
  ServerListRefreshInterval: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  server:
    port: 8081