version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - run:
          name: build ui service
          command: |
            cd ui
            mvn clean install docker:build docker:push

      - run:
          name: build hello-service
          command: |
            cd hello-service
            ./gradlew build docker dockerPush
      - run:
          name: build message-service
          command: |
            cd message-service
            ./gradlew build docker dockerPush