spring:
  main:
    cloud-platform: kubernetes
  application:
    name: ui-interface
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  server:
    port: 8081