apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-service
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |-
    hello-service-uri: http://message-service/message/random

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: hello-service
    app.kubernetes.io/name: hello-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.helloService.replicas }}
  selector:
    matchLabels:
  {{- include "hello-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "hello-service.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: hello-service
          image: "mrflick72/hello-service:{{ .Values.helloService.image.tag }}"
          imagePullPolicy: {{ .Values.helloService.image.pullPolicy }}
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
---

kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hello-service.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      name: http