kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: mongo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongodb/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
