kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    app: mongo
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongodb/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
