kind: ConfigMap
apiVersion: v1
metadata:
  name: ui-interface
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |-
    server:
      forward-headers-strategy: framework

    spring:
      data:
        redis:
          host: {{ .Release.Namespace }}-redis-master

      cloud:
        gateway:
          routes:
            - id: hello-service
              uri: lb://hello-service/
              predicates:
                - Path=/hello-service/**
              filters:
                - StripPrefix=1

            - id: message-service
              uri: lb://message-service/
              predicates:
                - Path=/message-service/**
              filters:
                - StripPrefix=1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-interface
  namespace: {{ .Release.Namespace }}
  labels:
    app: ui-interface
    app.kubernetes.io/name: ui-interface
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
  {{- include "ui-interface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "ui-interface.selectorLabels" . | nindent 8 }}
    
    spec:
      containers:
        - name: ui-interface
          image: "mrflick72/ui-interface:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
---

kind: Service
apiVersion: v1
metadata:
  name: ui-interface
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ui-interface.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ui-interface.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      name: http
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-interface-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ui.ingress.class }}
    {{- with .Values.ui.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-interface
                port:
                  number: 8080
      host: {{ .Values.ui.ingress.host }}
    {{- with .Values.ui.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}
